spin_manifest_version = 2

[application]
authors = ["Antoni Dikov"]
name = "Blocksense Oracle Example"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
sequencer = "http://sequencer:8877/post_report"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
reporter_id = 0

[[trigger.oracle]]
component = "aviationstack-api-fetcher"

[[trigger.oracle.data_feeds]]
id = "31"
data = "FR1730"

[component.aviationstack-api-fetcher]
source = "target/wasm32-wasi/release/aviationstack_oracle.wasm"
allowed_outbound_hosts = ["https://api.aviationstack.com:443"]
[component.aviationstack-api-fetcher.build]
command = "cargo build --target wasm32-wasi --release"
